### ISSUE TITLE
Get-AutopilotDevice() - the issue with space(s) in the serial number 

### ISSUE THREAD

**Issue by najki78** [andrew-s-taylor/WindowsAutopilotInfo#1]
Hello Andrew, 
I have dealt with the same issue recently (it is on Microsoft side) and since the trick with '[uri]::EscapeDataString($serial)' does not work unfortunately, the solution was to do it in two parts:
```
# get all the devices with the same (up to a first space) serial number 
$SerialWithoutSpace = $serial.split(" ")
$uri = "https://graph.microsoft.com/$graphApiVersion/$($Resource)?`$filter=contains(serialNumber,'$($SerialWithoutSpace[0])')"
```
and then to filter the device with the exact serial number:
```
$devicesResponse.value | Where-Object {$_.serialNumber -eq "$($serial)"}
```

**Comment by andrew-s-taylor** [comment]
I've just updated to v3.7 which adds your fix.  I've added some logic around it to it checks for spaces first.
Can you see if that works any better?  I don't have any devices with spaces in the serials to test with
Thank you

**Comment by najki78** [comment]
Hello Andrew,
wow, that was super fast! Thank you.
I have just tested (my lab VMware virtual machines have spaces in the names) and I would suggest one small change:
Instead of 
`$devices = $response.value`
to replace by
```
if ($serialhasspaces -eq 1) {  
     $devices = $response.value | Where-Object {$_.serialNumber -eq "$($serial)"}
} else {
     $devices = $response.value 
}
```

**Comment by andrew-s-taylor** [comment]
Well spotted, added on 3.8
