### ISSUE TITLE
Invoke-MGGraphRequest 400 Bad Request

### ISSUE THREAD

**Issue by jimmywinberg** [andrew-s-taylor/WindowsAutopilotInfo#11]
Running: Get-WindowsAutopilotInfoCommunity -Online -TenantId $tenantId -AppId $appId -AppSecret $StoredSecret -GroupTag $GroupTagValue

Invoke-MGGraphRequest : GET https://graph.microsoft.com/beta/devices%3F%24skiptoken%XXXXXXXXX
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: XXXXXXX
client-request-id: XXXXXXXXX
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"AM4PEPF0001511F"}}
Date: Mon, 11 Dec 2023 16:27:42 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"BadRequest","message":"Resource not found for the segment 'devices?$skiptoken=XXXXXXXXXXXXX'.","innerError":{"date":"2023-12-11T16:27:43","request-id":"XXXXXXXXXX","client-request
-id":"XXXXXXXXXXXX"}}}
At C:\Program Files\WindowsPowerShell\Scripts\get-windowsautopilotinfocommunity.ps1:1933 char:35
+ ... Response = (Invoke-MGGraphRequest -Uri $alloutputNextLink -Method Get ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...870d14de1b29
}:HttpRequestMessage) [Invoke-MgGraphRequest], HttpResponseException
    + FullyQualifiedErrorId : InvokeGraphHttpResponseException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest
Adding New Device serial XXXXXXXX
Waiting for 1 of 1 to be imported

**Comment by andrew-s-taylor** [comment]
Looks like it is failing when grabbing the existing devices, might be worth checking the permissions on your app reg

**Comment by jimmywinberg** [comment]
Thank you will check this out, the app have been working for months so not sure why it needs new permissions. But i will look into this tomorrow.
________________________________

**Comment by jimmywinberg** [comment]
Just tried giving it even more permissions, same issue.

Device.ReadWrite.All
DeviceManagementConfiguration.ReadWrite.All
DeviceManagementManagedDevices.PrivilegedOperations.All
DeviceManagementManagedDevices.ReadWrite.All
DeviceManagementServiceConfig.ReadWrite.All

Not sure what permission I'm missing here
________________________________
Från: Andrew Taylor ***@***.***>
Skickat: den 11 december 2023 17:46
Till: andrew-s-taylor/WindowsAutopilotInfo ***@***.***>
Kopia: Jimmy Winberg ***@***.***>; Author ***@***.***>
Ämne: Re: [andrew-s-taylor/WindowsAutopilotInfo] Invoke-MGGraphRequest 400 Bad Request (Issue #11)


Looks like it is failing when grabbing the existing devices, might be worth checking the permissions on your app reg

**Comment by andrew-s-taylor** [comment]
Can you try v4.0.4 which I have just uploaded and see if that works?  Looks like something has broken in the latest Graph SDK

**Comment by jimmywinberg** [comment]
Working perfectly now.
Super fast fix, tank you Andrew
________________________________
Från: Andrew Taylor ***@***.***>
Skickat: den 11 december 2023 18:47
Till: andrew-s-taylor/WindowsAutopilotInfo ***@***.***>
Kopia: Jimmy Winberg ***@***.***>; Author ***@***.***>
Ämne: Re: [andrew-s-taylor/WindowsAutopilotInfo] Invoke-MGGraphRequest 400 Bad Request (Issue #11)


Can you try v4.0.4 which I have just uploaded and see if that works? Looks like something has broken in the latest Graph SDK

**Comment by act-GH** [comment]
> Can you try v4.0.4 which I have just uploaded and see if that works? Looks like something has broken in the latest Graph SDK

Where can I find v4.0.4? Last I can see if 4.0.3.

**Comment by andrew-s-taylor** [comment]
Should be there now

**Comment by andrew-s-taylor** [comment]
I'm trying to work out what has broken in 2.0.11 of the auth module.
2.0.10 will work ok if it's urgent

**Comment by act-GH** [comment]
Assuming you mean v2.10.0 of microsoft.graph.authentication, I tried forcing that version and the error remains.

**Comment by andrew-s-taylor** [comment]
Can you try 2.9.1, it definitely works on that version.  Something has broken in pagination after that

**Comment by act-GH** [comment]
2.9.1 isnt erroring out immediately but it is taking a lot longer on the 'loading all objects' step than it used to. We have 100k+ devices so Ill give it time. As of last week I had successfully used v3.0.5 of the community script and it must have been using 2.10.0 of graph auth.

**Comment by andrew-s-taylor** [comment]
This should be resolved in the new 2.11.1 graph authentication module
