### ISSUE TITLE
Problem with preprov

### ISSUE THREAD

**Issue by Oneill701** [andrew-s-taylor/WindowsAutopilotInfo#14]
Hello,

Maybe I do something wrong but when I run this during OOBE : 
get-windowsautopilotinfocommunity -GroupTag "HAADJ" -Assign -AssignedUser "XXXX@XXX.com" -Preprov -Online

Everything works except redirecting to the white glove options.

If I physically do the 5 times on windows key, it works.

I have a french computer but I don't there is an impact on this.

Thanks for your work done on this script. ;-)

**Comment by andrew-s-taylor** [comment]
Hi,

This is one I'm working on, it's sending the keystrokes, but to the PowerShell window, so I'm just trying to work out how to send them to the OOBE screen instead

**Comment by andrew-s-taylor** [comment]
Looks like it needs the full Win key rather than combined keys so I've used AutoIt instead, script will now grab the exe and run it which should work
Full AutoIt code included as well in case of any security concerns

**Comment by Oneill701** [comment]
Thanks. I will try soon. ;-)

**Comment by andrew-s-taylor** [comment]
Has the autoit exe downloaded ok?

**Comment by Oneill701** [comment]
The file is download ok at Temp\preprov. I don't if it works correctly. When I double click on it, it doing nothing.

I try by letting the powershell open, like that : 
![IMG_20240325_165720](https://github.com/andrew-s-taylor/WindowsAutopilotInfo/assets/102239239/3b4f2b8d-db26-45d3-a94d-93b02fceedd3)
And I try the same command by reduce the powershell window to come back on the regional choice and wait, but nothing neither.

For information, I run this command : 
`get-windowsautopilotinfocommunity.ps1 -GroupTag "HAADJ" -Online -Assign -preprov`

**Comment by andrew-s-taylor** [comment]
Can you check what the window name is called?  It could be the different language which is stopping it from triggering

**Comment by Oneill701** [comment]
I'm not sure I understood correctly, but the window name it's Windows 10 Professionnel. It's a french version.

**Comment by andrew-s-taylor** [comment]
It has to send the keystrokes to a particular windows, it is looking for one called:
WinWait("Microsoft account")
WinActivate("Microsoft account")

Can you check if it has the same name in the French version?  If the name differs, the executable won't do anything

**Comment by Oneill701** [comment]
Ok sorry I understand now.
The name of the window is "Compte Microsoft".
![IMG_20240326_111207](https://github.com/andrew-s-taylor/WindowsAutopilotInfo/assets/102239239/436a79c8-a18b-4383-9f9d-b34bdba7d39c)

**Comment by andrew-s-taylor** [comment]
Ah, that will be the problem, I'll see if I can make it multi-language
