### ISSUE TITLE
Get-AutopilotDevice - Microsoft.Graph.PowerShell.Authentication.Helpers.HttpResponseException: Response status code does not indicate success: Forbidden (Forbidden).

### ISSUE THREAD

**Issue by SkrrtNick** [andrew-s-taylor/WindowsAutopilotInfo#18]
When I try to run Get-AutopilotDevice I get the following output:
```
Get-AutopilotDevice : Microsoft.Graph.PowerShell.Authentication.Helpers.HttpResponseException: Response status code
does not indicate success: Forbidden (Forbidden).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
At line:1 char:1
+ Get-AutopilotDevice
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AutopilotDevice
```

I'm authenticated as a Global Admin and use Connect-MgGraph to sign in

**Comment by andrew-s-taylor** [comment]
Hi,
Are you specifying scopes on your connection?  It you don't send a connection first, it should connect for you with the correct scopes configured

**Comment by SkrrtNick** [comment]
> Hi, Are you specifying scopes on your connection? It you don't send a connection first, it should connect for you with the correct scopes configured

No I've not configured scopes

**Comment by SkrrtNick** [comment]
Ah I think I was still using the non-community version, I apologise for my hastiness in opening an issue
