### ISSUE TITLE
Error when using identifier option

### ISSUE THREAD

**Issue by Thuurke** [andrew-s-taylor/WindowsAutopilotInfo#21]
Installed version: 5.0.2
Used command:
get-windowsautopilotinfocommunity.ps1 -Online -TenantId xxxxx -AppId xxxxx -AppSecret xxxxx -Identifier

https://graph.microsoft.com/DeviceManagementServiceConfig.ReadWrite.All is applies to the AppId

I get these errors. Same errors if I "get-windowsautopilotinfocommunity.ps1 -Online -Identifier" is executed and logged on with an admin account.

Checking if device xxxxx exists in AutoPilot
Invoke-MgGraphRequest : POST https://graph.microsoft.com/beta/deviceManagement/importedDeviceIdentities/searchExistingIdentities
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 81a461d5-60ed-47da-9c60-f50785091349
client-request-id: b6fac339-4abf-4459-b40e-1c3a92cc7b04
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"009","RoleInstance":"AM1PEPF00027E5A"}}
Date: Fri, 14 Jun 2024 08:45:14 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"Invalid Device Identifier parameter found for 1 import records! - Operation ID (for cu
stomer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b6fac339-4abf-4459-b40e-1c3a92cc7b04 - Url: https://fef.msub07.manage.microsoft.com/DeviceEnrollmentFE
/StatelessDeviceEnrollmentFEService/deviceManagement/importedDeviceIdentities/microsoft.management.services.api.searchExistingIdentities?api-version=5023-06-28\",\r\n  \"C
ustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2024-06-14T08:45:14","r
equest-id":"81a461d5-60ed-47da-9c60-f50785091349","client-request-id":"b6fac339-4abf-4459-b40e-1c3a92cc7b04"}}}
At C:\Program Files\WindowsPowerShell\Scripts\get-windowsautopilotinfocommunity.ps1:2014 char:18
+ ... response = (Invoke-MgGraphRequest -Uri $uri -Method Post -Body $json  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: POST, R...ication/json
}:HttpRequestMessage) [Invoke-MgGraphRequest], HttpResponseException
    + FullyQualifiedErrorId : InvokeGraphHttpResponseException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest
Device xxxxx does not exist in AutoPilot, adding it
Invoke-MgGraphRequest : POST https://graph.microsoft.com/beta/deviceManagement/importedDeviceIdentities/importDeviceIdentityList
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 64d8e02d-48a4-43dd-b83b-1e3342e94c1c
client-request-id: cc610bc6-abeb-4231-9a4a-6931046c7377
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"009","RoleInstance":"AM1PEPF00027E5A"}}
Date: Fri, 14 Jun 2024 08:45:14 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-0
00000000000 - Activity ID: cc610bc6-abeb-4231-9a4a-6931046c7377 - Url: https://fef.msub07.manage.microsoft.com/DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/device
Management/importedDeviceIdentities/microsoft.management.services.api.importDeviceIdentityList?api-version=5023-06-28\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryA
fter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2024-06-14T08:45:14","request-id":"64d8e02d-48a4-43dd-b83b-1e3342
e94c1c","client-request-id":"cc610bc6-abeb-4231-9a4a-6931046c7377"}}}
At C:\Program Files\WindowsPowerShell\Scripts\get-windowsautopilotinfocommunity.ps1:2060 char:1
+ Invoke-MgGraphRequest -Uri $uri -Method Post -Body $json -OutputType  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: POST, R...ication/json
}:HttpRequestMessage) [Invoke-MgGraphRequest], HttpResponseException
    + FullyQualifiedErrorId : InvokeGraphHttpResponseException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest
Device xxxxx added to AutoPilot

**Comment by andrew-s-taylor** [comment]
The corporate identifers for Windows have been removed from Intune, this won't work until the functionality has returned

**Comment by Thuurke** [comment]
Oke then we will have to wait. :)

**Comment by andrew-s-taylor** [comment]
This should be working now
