### ISSUE TITLE
Not requesting enough permissions

### ISSUE THREAD

**Issue by BenHagueNZ** [andrew-s-taylor/WindowsAutopilotInfo#3]
I had to change line 1893 to $graph = Connect-MgGraph -scopes Group.ReadWrite.All, Device.Read.All, DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementServiceConfig.ReadWrite.All
and line 1896 to $aadId = Connect-MgGraph -scopes Group.ReadWrite.All, Device.Read.All,DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementServiceConfig.ReadWrite.All in order to be able to add a device successfully. Otherwise I was getting a 403 error. I'd never used the previous script from MS on this tenant, so possibly different sets of permissions being requested?

**Comment by andrew-s-taylor** [comment]
Added now :)
