### ISSUE TITLE
online option with grouptag for existing windows autopilot devices doesn't update GroupTag

### ISSUE THREAD

**Issue by thiagobeier** [andrew-s-taylor/WindowsAutopilotInfo#4]
all parameters are working fine for brand new devices

if we run
**; brand new devices to windows autopilot**
.\get-windowsautopilotinfo-v1.ps1 -Online -TenantId aaaa -AppId bbbb -AppSecret cccc -**GroupTag** HYBRID -Verbose

**; existing devices in windows autopilot (we want only update existing GroupTag)**
;brand new device to windows autopilot
.\get-windowsautopilotinfo-v1.ps1 -Online -TenantId aaaa -AppId bbbb -AppSecret cccc **-Assign -GroupTag** HYBRID -Verbose

if we run the functions separately works 

**Get-AutopilotDevice** | Where-Object { $_.serialnumber -eq "VM" }
**Set-AutopilotDevice** -id 58bdc576-d87f-41a3-aec4-9cba1177a19c -groupTag "HYBRID"
**Invoke-AutopilotSync**
**Get-AutopilotDevice** | Where-Object { $_.serialnumber -eq "VM" }

**Comment by andrew-s-taylor** [comment]
V1.0.1 of community version now looks for the device, if it exists, just updates the group tag

**Comment by thiagobeier** [comment]
I've tested
it stops waiting for the Set-AutopilotDevice -id 

VERBOSE: Importing function 'Update-MgUserScopedRoleMemberOf'.
Connected to Intune tenant NNNNNNNNNNNNN using app-based authentication (Azure AD authentication not supported)
VERBOSE: Operation '' complete.
VERBOSE: Checking localhost
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = Win32_BIOS'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM
MDM_DevDetail_Ext01 WHERE InstanceID='Ext' AND ParentID='./DevDetail','queryDialect' = WQL,'namespaceName' =
root/cimv2/mdm/dmmap'.
VERBOSE: Operation 'Query CimInstances' complete.
Gathered details for device with serial number: **8547-1568-1987-0982-5331-6302-49 << vm serial number**
VERBOSE: GET https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities
VERBOSE: GET https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities with 0-byte
payload
VERBOSE: received 5763-byte response of content type application/json

cmdlet Set-AutopilotDevice at command pipeline position 1
Supply values for the following parameters:
id:

I'll try to figure it out somehow.

**Comment by andrew-s-taylor** [comment]
Pulled request
