### ISSUE TITLE
Function Get-AutopilotDevice() throwing error: Invoke-MgGraphRequest: The pipeline has been stopped.

### ISSUE THREAD

**Issue by Sn00zEZA** [andrew-s-taylor/WindowsAutopilotInfo#6]
The Function Get-AutopilotDevice() is throwing an error: Invoke-MgGraphRequest: The pipeline has been stopped.

its with line 304 https://github.com/andrew-s-taylor/WindowsAutopilotInfo/blob/7fe10613188b71c6319331eb24cd2ed79258a519/Community%20Version/get-windowsautopilotinfocommunity.ps1#L304C13-L304C89

**Comment by andrew-s-taylor** [comment]
How are you connecting to Graph in the script?

**Comment by Sn00zEZA** [comment]
> How are you connecting to Graph in the script?

App-based authentication

**Comment by Sn00zEZA** [comment]
Wrapping Get-WindowsAutoPilotInfoCommunity as function in script. Retrieving appid, appsecret and grouptag from AzureKeyVault after authentication

$AutopilotParams = @{
    Online = $true
    TenantId = $($azAccountContext.tenant.id)
    AppId = ($appSecretKey).AppId
    AppSecret = ($appSecretKey).AppSecret
    GroupTag = $($groupTagSelect.Value)
    Assign = $True
}
Get-WindowsAutoPilotInfoCommunity @AutopilotParams

Using default $Name variable "localhost" as the script is run on the machine being imported.
All device info collected correctly.
Do get the message "Connected to Intune tenant ###### using app-based authentication  (Azure AD authentication not supported)"

**Comment by andrew-s-taylor** [comment]
It seems to be a clash with the latest version of az.accounts and microsoft.graph.authentication modules.
You'll need to raise that one with Microsoft as I have no control over their modules.

**Comment by Sn00zEZA** [comment]
so change from az.accounts module to invoke-restmethod can work?

**Comment by andrew-s-taylor** [comment]
In the meantime, if you rollback the az.accounts module, it should start working again

**Comment by Sn00zEZA** [comment]
will run a test with az.keyvault version 4.9.3
