### ISSUE TITLE
asking to call connect-mggraph

### ISSUE THREAD

**Issue by thiagobeier** [andrew-s-taylor/WindowsAutopilotInfo#7]
run the following:

.\get-windowsautopilotinfo.ps1 -Hybrid -TenantId 111111 -AppId 22222 -AppSecret 33333 -AssignedComputerName "USAL-DEVICE1" -AddToGroup "USAL-AADJ" -Reboot -verbose 

**then goes:**

Select-MgProfile : The term 'Select-MgProfile' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\temp\get-windowsautopilotinfo.ps1:1890 char:13
+             Select-MgProfile -Name Beta
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Select-MgProfile:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Connect-MgGraph : Cannot bind parameter 'AccessToken'. Cannot convert the

**then connects**

At C:\temp\get-windowsautopilotinfo.ps1:1891 char:52
+             $graph = Connect-MgGraph  -AccessToken $accessToken
+                                                    ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MgGraph], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
 
Connected to Intune tenant 1111111111111111-22222-33333-44444-555555555555555 using app-based authentication (Azure AD authentication not supported)

and throws the error 

Add-AutopilotImportedDevice : Microsoft.Graph.PowerShell.AuthenticationException: Authentication needed. Please call Connect-MgGraph.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
At C:\temp\get-windowsautopilotinfo.ps1:2026 char:26
+ ... imported += Add-AutopilotImportedDevice -serialNumber $_.'Device Seri ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-AutopilotImportedDevice
 
if you stay on the same screen on the fresh device / VM

and run Connect-MgGraph

**than re-run enrollment parameters works** 

.\get-windowsautopilotinfo.ps1 -Hybrid -TenantId 111111 -AppId 22222 -AppSecret 33333 -AssignedComputerName "USAL-DEVICE1" -AddToGroup "USAL-AADJ" -Reboot -verbose 

after that device is ok and has its device name added to the windows autopilot device object, also has its GroupTag and get the windows autopilot deployment profile assigned as well as gets the proper DeviceName from AssignedComputerName parameter.

thanks,
Thiago Beier

**Comment by andrew-s-taylor** [comment]
You need to use the community version, this one hasn't been updated to work with v2 of the sdk
