### ISSUE TITLE
possible to remove a userPrincipalName in the autopilot nuke script? 

### ISSUE THREAD

**Issue by vacuumboots** [andrew-s-taylor/WindowsAutopilotInfo#9]
Hey, 
 There is a section 
 
 `$newuserPrincipalName = Read-Host -Prompt "Change assigned user [$userPrincipalName] (type a new value or hit enter to keep the old one)"
if (![string]::IsNullOrWhiteSpace($newuserPrincipalName)){ $userPrincipalName = $newuserPrincipalName }`

where the assigned user can be left as the user previously associated, or change to a new user. In the scenario where there was previously a user associated and now there should be no assigned user, its it possible to add an elseif statement for answering the prompt with a keyword like NONE to set the userprincipalname to null? 

Thanks,

**Comment by andrew-s-taylor** [comment]
Good idea, I've added into 3.6, can you check that works ok?

**Comment by vacuumboots** [comment]
Absolutely, I'll give it a shot tomorrow!
